language: node_js
node_js:
  - "10.14.2"

cache:
  directories:
    - node_modules
  yarn: false

os:
  - osx
  - linux

addons:
   apt:
     packages:
       - libsecret-1-dev
 
before_install:
  - rm -fr package-lock.json
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm i -g vsce
  - npm install
  - npm run vscode:prepublish

script:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      npm dedupe;
    fi
  - npm run lint
  - npm test --silent
  - vsce package -o LiveServer-$TRAVIS_TAG-$TRAVIS_OS_NAME.vsix

deploy:
  provider: releases
  api_key: $github_token
  file: "*.vsix"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
